### ISSUE TITLE
能否增加中文翻译

### ISSUE THREAD

**Issue by cuijianzhuang** [EventGhost/EventGhost#413]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by per1234** [comment]
Google Translate translation of title:
https://translate.google.com/#view=home&op=share&sl=auto&tl=en&text=%E8%83%BD%E5%90%A6%E5%A2%9E%E5%8A%A0%E4%B8%AD%E6%96%87%E7%BF%BB%E8%AF%91
>Can Chinese translation be added

**Comment by kdschlosser** [comment]
可能是您认识某个可以翻译的人

**Comment by liuxilu** [comment]
> 可能是您认识某个可以翻译的人

Neither Chinese nor English users can read Googlese... Original words please.

**Comment by wjjsn** [comment]
I have already translate it，but i do not understand how to package text to exe.
[zh_ZH.txt](https://github.com/user-attachments/files/16241444/zh_ZH.txt)

**Comment by Paderman** [comment]
> I have already translate it，but i do not understand how to package text to exe.

I can't Chinese, but I compiled the file for you 😉
I fixed some format errors in .py file.

For compiling use `python -m py_compile zh_ZH.py`

### Contents of EventGhost_language_zh_ZH.zip
- languages\zh_ZH.py
- languages\zh_ZH.pyc
- images\flags\zh_ZH.png

### Download package
[EventGhost_language_zh_ZH.zip](https://github.com/user-attachments/files/21674141/EventGhost_language_zh_ZH.zip)
### Checksum
SHA-512: 94b87319830da45d062d3ddbbc93cf73e9c9b3042544d72d452acf66e066ffafdedefd6575026083ba564336f011fdfa7d6bbc10173cc8c6e31cef09545ef90a
### Copying
Copy all contents to `%ProgramFiles(x86)%\EventGhost`

**Comment by wjjsn** [comment]
> > I have already translate it，but i do not understand how to package text to exe.
> 
> I can't Chinese, but I compiled the file for you 😉 I fixed some format errors in .py file.
> 
> For compiling use `python -m py_compile zh_ZH.py`
> 
> ### Contents of EventGhost_language_zh_ZH.zip
> * languages\zh_ZH.py
> * languages\zh_ZH.pyc
> * images\flags\zh_ZH.png
> 
> ### Download package
> [EventGhost_language_zh_ZH.zip](https://github.com/user-attachments/files/21674141/EventGhost_language_zh_ZH.zip)
> 
> ### Checksum
> SHA-512: 94b87319830da45d062d3ddbbc93cf73e9c9b3042544d72d452acf66e066ffafdedefd6575026083ba564336f011fdfa7d6bbc10173cc8c6e31cef09545ef90a
> 
> ### Copying
> Copy all contents to `%ProgramFiles(x86)%\EventGhost`

Thank you so much, I really didn't expect such a long message would still get a reply. There are still many good people in this world.
